### ISSUE TITLE
Console error when there is no menu on the page

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Documentation/sphinx_typo3_theme#114]
If you have a template with no toc menu, then JS is throwing an error:

theme.min.js:formatted:8 Uncaught TypeError: Cannot read property 'getElementsByTagName' of null
    at makeMenuExpandable 

in makeMenuExpandable there should be a check if there are any elements with class toc at all.

```
var tocs = document.getElementsByClassName('toc');
```

**Comment by marble** [comment]
Ah, thank you for the explanation, that's why it didn't come up during testing and on our docs pages. But you're definitely right, that's an error from my side, and I'm going to fix that soon. However, we don't need to deploy and emergency bugfix release just for this. I'm very thankful for any kind of feedback or error report like this.

**Comment by tmotyl** [comment]
Correct, no hotfixing needed

**Comment by marble** [comment]
It's even better. This error is actually due to how the code is below v4.5. Now, with the Docker Rendering Container (DRC) I actually released that v4.5.1 version of the theme, in which I had touched that code to allow for multiple "toc" elements. And in doing so, I had already fixed that error. Only that I had not known that there had been an error.

Only newly rendered manuals are rendered with DRC v2.8.0 including theme v4.5.1. There had been some problems with the Bamboo machines, so Susi didn't want to stress them by re-rendering all manuals. [Check this one for an example](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocsOfficial/GithubMethod.html#docs-contribute-github-method)

So: please use the latest version v4.5.1 of the theme and the error should be gone.

**Comment by marble** [comment]
This has already been fixed in the most recent versions v4.5.x
