### ISSUE TITLE
Problem with search: auto-expands search term to wrong term

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/sphinx_typo3_theme#116]
# Reproduce

1. Go to changelog https://docs.typo3.org/c/typo3/cms-core/master/en-us/
2. Type `sys_language_content` in search box
3. Now a suggestion is displayed (do not select this)

![image](https://user-images.githubusercontent.com/13206455/112447087-32dace80-8d51-11eb-8a69-c56a14b554a0.png)

4. Just hit enter

## Result

The search term is replaced with `sys_language_contentol`. 

This is not what I want.

**Comment by jonaseberle** [comment]
IMHO this has been like that since the new search was implemented. 

As a workaround: You can close the dropdown with `ESC`.

**Comment by marble** [comment]
This is mainly a documentation problem. 

## Understanding the built in Sphinx offline search

Actually the builtin offline search is very cool, as it answers - correctly! - the question, which page contain the searchstring. You still have to check each page for all occurrences though.

The search answers the question, which pages can tell me something about my search string.

- That search originally doesn't have autocompletion.
- But since autocompletion may help a lot and somebody invented code for that it is made available.
- The search database only contains the word stem and has it's own additional information, like [this one](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/_static/language_data.jslist) for example.
- Autocompletion is only looking at the word stem. If you want to use autocompletion, select one entry from the list first, exactly as it is proposed, then do a second click to actually search.
- In this case we have: 
![image](https://user-images.githubusercontent.com/307057/112460167-e4343100-8d5e-11eb-9b63-6c68fe817ed1.png)
- This will give you what you want: 
![image](https://user-images.githubusercontent.com/307057/112460410-25c4dc00-8d5f-11eb-8b0b-e28bffe7c4de.png)
- You may as well type the whole word, but, as you see, the autocompletion proposal is there and will take effect if you just press enter: 
![image](https://user-images.githubusercontent.com/307057/112460656-6cb2d180-8d5f-11eb-871b-66ecceeab293.png)
- To avoid the wrong item from the autocompletion list type one more trailing blank. That kills the proposal: 
![image](https://user-images.githubusercontent.com/307057/112460934-b7cce480-8d5f-11eb-8a47-1812ed8edf8d.png)
- And voilà, you get what you are looking for: 
![image](https://user-images.githubusercontent.com/307057/112461078-e054de80-8d5f-11eb-970b-edd646b43168.png)

To complete this documentation:

- Read the results as: This list is giving me all pages that contain my search word.
- And when I visit a result page, the search string is highlighted:
![image](https://user-images.githubusercontent.com/307057/112461526-493c5680-8d60-11eb-8d15-ca8f98f3d0af.png)

- If there are too many occurrences and the highlighting is annoying, it can be turned off:
![image](https://user-images.githubusercontent.com/307057/112461790-93253c80-8d60-11eb-855b-b1143b6d68b8.png)

**Comment by marble** [comment]
The above explanation should go to our documentation. What would be the right place to put it?

**Comment by jonaseberle** [comment]
Why so complicated? IMHO this is simply a UX bug that can be just fixed.

**Comment by sypets** [comment]
I agree with @jonaseberle here. 

> This is mainly a documentation problem.

I think 99% of the people using the search will NOT read the documention - even if it is easy to find.

I think the usage should comply with modern usability (and accessibility) principles and do what will be expected.

I had a problem using this - but I shouldn't be the factor here, neither should any of us. The docs is used by the entire TYPO3 community. I think important is that the search is easily usable and does what people expect in most cases. This should not be a question of personal preferences but what works and complies to usability (as well as accessibility) best practices.

**Comment by sypets** [comment]
In my example above, sys_language_content was not in the autosuggest list. It was not possible to search for this string (unless ESC was pressed, which Jonas pointed out). If I am just too stupid to use autosuggest and everyone else is happy with it, that is fine with me. But if this can be improved, it would be great.

(The other question is, why sys_language_content is not in the autosuggest list, it is definitely in the changelog).

**Comment by jonaseberle** [comment]
Yes, the other problem is that search term suggestion is sometimes (rather often in my experience) not providing the correct word although it is in the content. I opened an issue in order to get some data points: https://github.com/TYPO3-Documentation/sphinx_typo3_theme/issues/118

**Comment by sypets** [comment]
Another question is, why is `sys_language_cont` not displayed as results for autosuggest when `sys_langauge_content` is typed in?

Example 1: Type in `sys_language_content`

Result:
* sys_language_content_ol


Example 2: Type in `sys_language`

Result:

* sys_language_cont
* sys_language_contentol
* etc.

So it looks like there is a language stem sys_language_cont but is not displayed for sys_language_content. Why?
