### ISSUE TITLE
Scrollbar within `table-responsive`

### ISSUE THREAD

**Issue by simonschaufi** [TYPO3-Documentation/sphinx_typo3_theme#136]
Browser: Google Chrome 91
OS: Ubuntu

Doesn't depend on window size. Even when I'm scaling it down to mobile view the scrollbar is still there. I've noticed that it appears the moment the privacy settings button appears. Inkognito mode also the same.

If i block all network requests to:

- api.usercentrics.eu
- aggregator.service.usercentrics.eu

then the scrollbar doesn't appear.

![image](https://user-images.githubusercontent.com/941794/125939795-4f12cf04-90be-48ef-ab01-623dbcf5c7dd.png)

**Comment by marble** [comment]
I assume the problem is gone. For example, here https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/Index.html, Ubuntu 20.04, Version 100.0.4896.60 (Offizieller Build) (64-Bit), I have:
![grafik](https://user-images.githubusercontent.com/307057/161573535-94f25a89-c7ef-4040-af90-b23a32db93e8.png)
So I assume it's solved.

**Comment by simonschaufi** [comment]
@marble yes. Looks like expected.
