### ISSUE TITLE
Show name of current manual in placeholder in search box

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/sphinx_typo3_theme#45]
Initially, https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/issues/81 suggested to change the text slightly in the search input field (change "search this project" to "search this document"). 

Proposal: Change text in search box to include  name of current manual, e.g. 

![search1](https://user-images.githubusercontent.com/13206455/73353483-b6a34300-4293-11ea-9393-1cedd47759d1.png)

to

![search2](https://user-images.githubusercontent.com/13206455/73353581-f23e0d00-4293-11ea-93c5-d8372d535421.png)

**Comment by marble** [comment]
Good idea. But, on the other hand: Is it worth the effort? Since the placeholder text often cannot be seen in total. Consider: 
![grafik](https://user-images.githubusercontent.com/307057/100469217-1cd83c80-30d6-11eb-9aab-b2e290e1caad.png)

I tend to say: That's not worth the effort to tackle that in the theme. Especially, with, hopefully, a global search in mind to come in 2021.
