### ISSUE TITLE
[Questions] Local versus documentation setup

### ISSUE THREAD

**Issue by s0h3ck** [TYPO3-Documentation/sphinx_typo3_theme#49]
Hello, I am exploring Sphinx and I tried your package. I am curious how to get the result in your documentation [here](https://docs.typo3.org/m/typo3/demo-t3SphinxThemeRtd/master/en-us/).

My setup is a default setup following the Sphinx documentation with conf.py and index.rst in the source directory.

**Question 1**: How do I maximize the space?

Me:

![1581174471](https://user-images.githubusercontent.com/7539558/74091389-d239f500-4aae-11ea-83e3-138f2cce5b43.png)

The documentation:

![1581174496](https://user-images.githubusercontent.com/7539558/74091387-cea66e00-4aae-11ea-9252-48e41e59a866.png)

**Question 2**: How does nested toctree work? For example, the block quotes does not have plus or minus button in my local version, but it has one in the documentation.

Me:

![1581175747](https://user-images.githubusercontent.com/7539558/74091669-c865c100-4ab1-11ea-8fb4-085bd6f71441.png)

The documentation:

![1581175735](https://user-images.githubusercontent.com/7539558/74091671-cd2a7500-4ab1-11ea-96d7-c3d88b2d205b.png)

**Question 3**: Are you still using Python 2? The `sphinxcontrib.youtube` didn't work for me. I had to install `sphinxcontrib.yt`. `sphinxcontrib.yt` is apparently an updated version for Python 3. The documentation mentions `sphinxcontrib.youtube`, so it may be a mistake in the documentation. Which library do you use?

**Comment by marble** [comment]
In the TYPO3 community we are using Sphinx for documentation:
https://docs.typo3.org  In the footer you'll find the link to the currently used theme https://github.com/TYPO3-Documentation/t3SphinxThemeRtd which builds on the ReadTheDocs theme.
We are using this docker container for rendering: https://github.com/t3docs/docker-render-documentation You can use that container or study the recipe.
Right now we are in a transition phase to move to this brand new 'sphinx_typo3_theme' here. It is still work in progress, but already integrated - in a suboptimal way - in the 'develop' version of the Docker container.
The container is still using Python2 at the moment, because the "TCT" and "Toolchain" need to be refactored and adapted to Python 3 first.
Hope that helps!

**Comment by s0h3ck** [comment]
Hi marble, thanks! Keep up the good work! :)
